### ISSUE TITLE
Add the possibilities to select a date range

### ISSUE THREAD

**Issue by AndroFlo** [vikramkakkar/SublimePicker#1]
Hello, 
Your library is very usefull with a good design.

Can you add the possibilite to select a range of dates like this library : http://android-arsenal.com/details/1/127

Thank you

**Comment by Rainer-Lang** [comment]
+1

**Comment by vikramkakkar** [comment]
I'll look into this as soon as I have some time.

**Comment by AndroFlo** [comment]
Thank you

**Comment by yoavst** [comment]
+1

**Comment by vikramkakkar** [comment]
@AndroFlo @yoavst 

`SublimePicker` now supports date-range selection.
