### ISSUE TITLE
prefix attributes such as firstDayOfWeek with sp

### ISSUE THREAD

**Issue by siderakis** [vikramkakkar/SublimePicker#10]
SublimeePicker has conflicting attributes with other libraries.  Some attributes are already prefixed with "sp", would it be possible to prefix all attributes with sp?

**Comment by vikramkakkar** [comment]
Yes, of course. I will roll this out asap.

**Comment by Rainer-Lang** [comment]
Thanks.

**Comment by Rainer-Lang** [comment]
@vikramkakkar And also thanks for this great lib!

**Comment by Rainer-Lang** [comment]
@siderakis You could make a pull request... ;-)

**Comment by vikramkakkar** [comment]
> Yes, of course. I will roll this out asap.

Hmm, took me 8 months. But, its done right with v2.0.0.
