### ISSUE TITLE
How to use and styling of pickers.

### ISSUE THREAD

**Issue by makk909** [vikramkakkar/SublimePicker#11]
I have gone through your sample app on playstore and it looks pretty good even in below lollipop devices. I really appreciate your work. It would be better if you  provide a bit more explanation regarding how to use and styling of pickers to suit app requirements. Also a gradle dependency for the library project will be much appreciated.

**Comment by vikramkakkar** [comment]
Thanks for your kind words!

Gradle dependency:

`compile 'com.appeaser.sublimepickerlibrary:sublimepickerlibrary:1.0.0'`

I have been pressed for time lately. The wiki is extremely lacking. If you have a specific question about styling, I can help you out. But, a whole styling tutorial will take at least a few days. This is really not what I had planned. 

My apologies.

**Comment by makk909** [comment]
Thanku very much for your reply, I really appreciate. I just want to know the sample code that how can we integrate both the date and time picker separately. Also how we can change the accent color of both the pickers so that it should match with the app theme/color.?

Thanks :)

**Comment by makk909** [comment]
Well I have customised your library according to my requirement but am not able to add it as a module dependency in my current project. It is giving me this error

Error:Plugin with id 'com.github.dcendents.android-maven' not found.

So can you please let me know what I am missing?

**Comment by Rainer-Lang** [comment]
@makk909 What did you customize?

**Comment by makk909** [comment]
Actually I changed the accent color and separated the datepicker,timepicker and recurrence picker from one another. Also made some changes to the layout of these. But now i want to use this library in one of my projects but I am not able to add this library as an module dependency in my project. When I do so am getting this error

Error:Plugin with id 'com.github.dcendents.android-maven' not found.

If i run your project, that runs perfectly but when i try to import the sublimepicker library even without making any changes in one of my projects it always give me this error. I urgently need this library to be added to my project but I am not able to do this. So can you please help me out?

**Comment by vikramkakkar** [comment]
Hi!

Let's try to solve your original problem.

> ...how can we integrate both the date and time picker separately.

So, you'd like to have 2 separate SublimePickers? One that only displays DatePicker, and the other only displays the TimePicker?

If that's the case, create 2 separate instances of SublimePickers. Use the following display options on the first picker:

    SublimeOptions options = new SublimeOptions();
    options.setDisplayOptions(SublimeOptions.ACTIVATE_DATE_PICKER);

For the second instance:

    SublimeOptions options = new SublimeOptions();
    options.setDisplayOptions(SublimeOptions.ACTIVATE_TIME_PICKER);
    options.setPickerToShow(SublimeOptions.Picker.TIME_PICKER);

For styling:

    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">

        <item name="sublimePickerStyle">@style/SPStyle</item>
    </style>

       <style name="SPStyle" parent="SublimePickerStyleLight">
        <item name="colorAccent">#D94818</item>
        <item name="colorPrimaryDark">#141414</item>
        <item name="colorPrimary">#212121</item>
        <item name="android:textColorPrimary">#212121</item>
        <item name="android:textColorSecondary">#727272</item>
        <item name="android:textColorPrimaryInverse">#FFFFFF</item>
    </style>

Change the accent color to app's colorAccent under `SPStyle`. 

Hope this helps.

**Comment by makk909** [comment]
But I also need recurrence picker with some layout changes and for that I have to make changes to your library. I can find other libraries for material design date picker and time picker but your is giving the option for recurrence picker as well. So that's why I preferred to use your library. But there are some changes that i have to make in the recurrence picker in terms of design and when i made that and everything works great, am not able to add it to my project. So can you sort out with that?

**Comment by Sai-Teja** [comment]
@makk909 Don't use Gradle Dependencies. Download the project and add it as a module in your project. It sorts Everything I guess.

**Comment by makk909** [comment]
Well am not using gradle dependency. I just downloaded the project , made
some changes in the library. The sample project that I downloaded from
github is working fine but am not able to use that changed library in my
required project.

**Comment by makk909** [comment]
Also I have notice that if I try to add the library project to my required
project even without making any changes it still gives me the same error

**Comment by Sai-Teja** [comment]
And the error was?

**Comment by Sai-Teja** [comment]
Simple! Actually It is trying to link to the gradle repository. remove all links to the repo in ur build.gradle of library and try it.

**Comment by Sai-Teja** [comment]
This is the build.gradle file I use. Try this!

apply plugin: 'com.android.library'

android {
    compileSdkVersion 22
    buildToolsVersion "22.0.1"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:22.2.1'
    compile 'com.android.support:support-v4:22.2.1'
}

**Comment by makk909** [comment]
Thanks for your help. But I'll try this code in the mrng. But I don't think
this will make any change because I too have the same build.gradle file for
the sublime picker library.  Also it is working fine in the sample project
on github but not when I make a new project and try to add the
sublimepicker library from the sample project into the newly created
project. I always get that plugin not found error.

**Comment by Sai-Teja** [comment]
The build file in sample project is different from this. Anyways try it!

**Comment by vikramkakkar** [comment]
Remove the following lines from the `build.gradle` file of `sublimepickerlibrary`:

   apply from: 'https://raw.githubusercontent.com/nuuneoi/JCenter/master/installv1.gradle'
apply from: 'https://raw.githubusercontent.com/nuuneoi/JCenter/master/bintrayv1.gradle'

Also remove the `ext` {…} block.

**Comment by Rainer-Lang** [comment]
@makk909 Maybe it's possible that you share some screenshots. I'm interested in your changes. :-)

**Comment by makk909** [comment]
@Sai-Teja and @vikramkakkar thanku so much for your help, removing that few lines from the build.gradle file does the trick. I wonder why i didn't try to dig into the build.gradle file earlier before asking this silly question here. Anyways thanks bros :)

**Comment by makk909** [comment]
@Rainer-Lang I just made all the three pickers independent from each other and made some layout changes in the pickers. So what do you actually want to see?

**Comment by Rainer-Lang** [comment]
I want to see your visual changes and/or your changes in the code. I'm interested in improving SublimePicker. Actually SP is good - but all could be improved ;-)

**Comment by makk909** [comment]
Okay so let me integrate it in my existing project and then i'll send you the screenshot :)

**Comment by Rainer-Lang** [comment]
Ok thank you. :-)

**Comment by Sai-Teja** [comment]
@makk909 U are welcome! This is the first issue I have solved !! :blush:

**Comment by makk909** [comment]
Hehe.. lol +1:
