### ISSUE TITLE
24h support a bit wrong

### ISSUE THREAD

**Issue by Rainer-Lang** [vikramkakkar/SublimePicker#13]
I use 24h and I also have the Date- and TimePicker.
DatePicker shows "4:47 NACHM." which is wrong for 24h.
It should be "16:47".

**Comment by vikramkakkar** [comment]
Are you talking about the button in the bottom-left corner? If so, `SublimePicker` already provides functionality to specify custom formatting rules. 

When defining the callback - `SublimeListenerAdapter` - override `formatDate(Date)` & `formatTime(Date)` methods. You can define your custom `DateFormat` and return the formatted `CharSequence` using the given `Date`. 

By default, these methods return `null`, and based on this `null` value, `SublimePicker` uses these default date & time formatters:

https://github.com/vikramkakkar/SublimePicker/blob/master/sublimepickerlibrary/src/main/java/com/appeaser/sublimepickerlibrary/SublimePicker.java#L102

You can see how these are initialized:

    mDefaultDateFormatter = DateFormat.getDateInstance(DateFormat.MEDIUM,
                Locale.getDefault());
    mDefaultTimeFormatter = DateFormat.getTimeInstance(DateFormat.SHORT,
                Locale.getDefault());
    mDefaultTimeFormatter.setTimeZone(TimeZone.getTimeZone("GMT+0"));

For your use case, `SimpleDateFormat` would be better. Final code may look like this:

    SimpleDateFormat sdfTime = new SimpleDateFormat("kk:mm");    

    /**
     * @param selectedTime The time of day that was set.
     * @return Formatted time to display on `Switcher` button
     */
    public CharSequence formatTime(Date selectedTime) {
        return sdfTime.format(selectedTime);
    }

**Comment by Rainer-Lang** [comment]
formatting is "working". But I have a wrong time.
I use ```java new Date().getTime() ``` "time=08:05" but then I want to format the time, so I get "time=09:05" in ```java formatTime(Date selectedTime) ```.

**Comment by Rainer-Lang** [comment]
formatting is working

BUT: I put initial time inside "08:32" and in formatTime(Date...) i get a time "09:32". That's not correct. Something with the timezone I think.

**Comment by vikramkakkar** [comment]
Use `HH(0 - 23)` instead of `kk`(1 - 24):

    SimpleDateFormat sdfTime = new SimpleDateFormat("HH:mm");

More info: [SimpleDateFormat](http://developer.android.com/reference/java/text/SimpleDateFormat.html)

**Comment by Rainer-Lang** [comment]
I use DateUtils - not SimpleDateFormat

**Comment by Rainer-Lang** [comment]
DateUtils.formatDateTime(context, calendar.getTimeInMillis(), DateUtils.FORMAT_SHOW_TIME);

**Comment by Sai-Teja** [comment]
Found it ppl !! the widget is returning 1hr less after Jan 19 2038 09:44. Fix it !! @vikramkakkar

**Comment by Rainer-Lang** [comment]
I think there is something wrong with the DST. I get 10:25 (in the morning) but it should be 9:25.
