### ISSUE TITLE
Can you specify how to parse custom reccurence rule?

### ISSUE THREAD

**Issue by Sai-Teja** [vikramkakkar/SublimePicker#14]
I mean can we convert recurrence rule back to Event recurrence object of ur library?
And what is the WKST Param in that?

**Comment by Sai-Teja** [comment]
I tried EventRecurrence.parse(recurrenceRule) but it is not working :(

**Comment by Sai-Teja** [comment]
Plz fix it fast I cant use ur library otherwise and other libraries are not as good as yours. :(

**Comment by Sai-Teja** [comment]
@vikramkakkar Plz fix it fast I cant use ur library otherwise and other libraries are not as good as yours. :(

**Comment by Sai-Teja** [comment]
@vikramkakkar Wait! its not working in debugger may be because of running asynchronusly. is it???
It is being called after the execution of the parse function line.

**Comment by Sai-Teja** [comment]
Plz tell me what is WKST ASAP!

**Comment by vikramkakkar** [comment]
@Sai-Teja `WKST` is Week-Start. Values that WKST can take are SU, MO, TU etc. Declarations are here:

https://github.com/vikramkakkar/SublimePicker/blob/master/sublimepickerlibrary/src/main/java/com/appeaser/sublimepickerlibrary/recurrencepicker/EventRecurrence.java

If you want to initialize the Recurrence Picker with a `recurrenceRule`, use `SublimeOptions.setRecurrenceParams(String)`.

Sorry about the delay in replying. I am quite busy with work these days.

**Comment by Sai-Teja** [comment]
@vikramkakkar and how to parse the until param of eventRecurrence to date?
