### ISSUE TITLE
Date cut from bottom

### ISSUE THREAD

**Issue by rishabhsri20** [vikramkakkar/SublimePicker#17]
While selecting dates like 9 or 30 it is cut from below...

**Comment by Rainer-Lang** [comment]
I don't see what you mean. Could you make a screenshot?

**Comment by rishabhsri20** [comment]
http://imgur.com/oBE8ORd

**Comment by Rainer-Lang** [comment]
Thanks. You have another font as "normal".

**Comment by vikramkakkar** [comment]
Unfortunately, this is a problem I already tried to address. 

If you open the stock Calendar app on version >= 21, you'll encounter a worse version of this problem - the clipping is very noticeable:

![sel](https://cloud.githubusercontent.com/assets/4239472/9607114/4e718d4a-5095-11e5-9395-eeb778340e3f.png)

My solution was to make the radius of the selection circle smaller. But, I guess we can't beat every device using this fix. 

The selection indicator size is defined here: [Link](https://github.com/vikramkakkar/SublimePicker/blob/master/sublimepickerlibrary/src/main/java/com/appeaser/sublimepickerlibrary/datepicker/SimpleMonthView.java#L219)

I'll check if if the size can be determined at runtime.

**Comment by vikramkakkar** [comment]
This is fixed with version 2.0.0.
