### ISSUE TITLE
onTouchListener Not Working

### ISSUE THREAD

**Issue by Sai-Teja** [vikramkakkar/SublimePicker#18]

**Comment by Sai-Teja** [comment]
Using setOntouchListener on SubLimePicker Class.

**Comment by vikramkakkar** [comment]
Could you please provide more information about what isn't working. Can you also include:

 - reason for setting an `OnTouchListener` on `SublimePicker`.
 - stacktrace in case of a crash
 - code that is _supposed_ to be working

**Comment by Sai-Teja** [comment]
I'm using the picker in nested Scroll View nd can't scroll when scrolling in the white area in radial time picker.

**Comment by Sai-Teja** [comment]
Can you guide me on how to do that

**Comment by Sai-Teja** [comment]
nd onTouch is not even called. I thought of passing the event to Nested Scroll View.

**Comment by vikramkakkar** [comment]
`RadialTimePickerView` sets its own `OnTouchListener`: [Link](https://github.com/vikramkakkar/SublimePicker/blob/master/sublimepickerlibrary/src/main/java/com/appeaser/sublimepickerlibrary/timepicker/RadialTimePickerView.java#L63)

And it captures all touch events by returing `true`: [Link](https://github.com/vikramkakkar/SublimePicker/blob/master/sublimepickerlibrary/src/main/java/com/appeaser/sublimepickerlibrary/timepicker/RadialTimePickerView.java#L1251)

To solve your problem, `RadialTimePickerView's onTouch(MotionEvent)` will have conditionally return `false`. The condition will be this: 

    private int getDegreesFromXY(float x, float y) {
        final double hypotenuse = Math.sqrt(
                (y - mYCenter) * (y - mYCenter) + (x - mXCenter) * (x - mXCenter));

        // Basic check if we're outside the range of the disk
        if (hypotenuse > mCircleRadius[HOURS]) {

            // If we are outside the range of the disk && action == MotionEvent.ACTION_DOWN,
            // return `false` from `onTouch(MotionEvent)`.
            return -1;
        }
        ....
        ....
    }

This may just be the beginning of a solution, and additional changes may be required. But, you can definitely give it a try.

**Comment by Sai-Teja** [comment]
@vikramkakkar I tried it before raising the issue itself. Making it return false in each and every case also wouldn't help. Plz Reply ASAP.
