### ISSUE TITLE
Please add 24h support

### ISSUE THREAD

**Issue by Rainer-Lang** [vikramkakkar/SublimePicker#2]

**Comment by vikramkakkar** [comment]
Are you referring to the 24-hour option in case of `TimePicker`? If so, its already supported. You can opt for it while initializing `SublimePicker` using `SublimeOptions#setTimeParams(int hourOfDay, int minute, boolean is24HourView)`. 

The wiki is still under construction, but this page lists other some more info on `SublimeOptions`: https://github.com/vikramkakkar/SublimePicker/wiki/SublimeOptions.

**Comment by joaosardinha** [comment]
Can you provide an exemple with this working?
