### ISSUE TITLE
Supporting API 14

### ISSUE THREAD

**Issue by fncapps** [vikramkakkar/SublimePicker#21]
Hi,
I'll love to use your library but I'd need it to work with API 14. Is there any hope to make it work with API 14?

I'd just need a simple DatePickerDialog, if I force the use of the library in my manifest... would it crash my app?

Thanks in advance

**Comment by connonfodder** [comment]
the same

**Comment by aadhk** [comment]
I also need to support API 14. I don't want to miss 10% of my users

**Comment by tuhin10** [comment]
+1

**Comment by WasimMemon** [comment]
+1, 
any update on this ?

**Comment by vikramkakkar** [comment]
@fncapps @connonfodder @tuhin10 @WasimMemon `SublimePicker` now supports API 14 & above.

**Comment by fncapps** [comment]
Thanks!!

I'll begin using it as soon as I can!

**Comment by vikramkakkar** [comment]
@fncapps You are welcome. Any feedback will be much appreciated!
