### ISSUE TITLE
Attributes already defined

### ISSUE THREAD

**Issue by simongiesen** [vikramkakkar/SublimePicker#24]
Hi,

great library!

When adding the library via gradle it's not possible to sync because of attributes already defined (e.g. firstDayOfWeek in conflict with com.baoyz.pullrefreshlayout). Any suggestions what to do?

**Comment by vikramkakkar** [comment]
@simongiesen It was flawed design. This has been addressed (and hopefully fixed!) in v2, which is now available. Gradle dependency has been added to `readme`.
