### ISSUE TITLE
Put it to Maven Repositories

### ISSUE THREAD

**Issue by Poeschl** [vikramkakkar/SublimePicker#4]
Do you intent to put your library to a artifact repository as jCenter or maven?

**Comment by Rainer-Lang** [comment]
Please put it to jCenter.

**Comment by vikramkakkar** [comment]
SublimePicker is now available on jCenter:

`compile 'com.appeaser.sublimepickerlibrary:sublimepickerlibrary:1.0.0'`

**Comment by Poeschl** [comment]
Nice, thanks a lot.
PS: don't forget to put this info on the Readme ;)

**Comment by Shusshu** [comment]
Publish it to maven too (via jcenter you can do that) and update readme :p

**Comment by valentin-sobolev** [comment]
Please update readme
