### ISSUE TITLE
Error in selected Date

### ISSUE THREAD

**Issue by lozo2010** [vikramkakkar/SublimePicker#40]
When selected july in your app, show month:6 -> June 
![photo_2016-07-19_08-53-38](https://cloud.githubusercontent.com/assets/9165283/16941098/5553d194-4d8e-11e6-9b91-4b4b72e6f5ea.jpg)
![photo_2016-07-19_08-53-48](https://cloud.githubusercontent.com/assets/9165283/16941100/57c86e76-4d8e-11e6-890c-a39f43149d46.jpg)

**Comment by Rainer-Lang** [comment]
Month starts with index 0

**Comment by CCorrado** [comment]
starts with index 0....unless you use JodaTime...in which case it will start at index 1...
