### ISSUE TITLE
Possibilty to return null as "no date selected"?

### ISSUE THREAD

**Issue by Rainer-Lang** [vikramkakkar/SublimePicker#5]
I need the possibilty to return that the user doesn't want to set a date.
I/the user start with "no date" and I need that the user also could go back to the initial value "no date".

**Comment by vikramkakkar** [comment]
Can you please clarify your request a bit more? 

So, you want the DatePicker to be active/available for date-selection, but have no initial date set? 

Btw, the option to disable the DatePicker is already available. But, I'm not sure if that's what you're looking for.

**Comment by Rainer-Lang** [comment]
I have a fragment where the user can define a start-date for a task.
Initially the start-date is empty (null) so I write in the EditText "immediately", which means the task will start immediatly after the user pressed "start task". BUT the user could save the task as draft - and start the task later.

Now the user can open DatePicker and pick another date - which I write in the edit.
If the user want to reset the start-date - he couldn't.

I need a start-date null. 
Maybe you have another great idea... ;-)

**Comment by Rainer-Lang** [comment]
Maybe a button with "none" in date- and timepicker?

**Comment by Rainer-Lang** [comment]
I solved this. I use a separated button to clear the EditText (date or time).
=> closing this issue.
