### ISSUE TITLE
How to disable past dates/times or also for future?

### ISSUE THREAD

**Issue by Rainer-Lang** [vikramkakkar/SublimePicker#7]

**Comment by vikramkakkar** [comment]
@Rainer-Lang `new Date().getTime()` should work fine for `minDate`. Passing `Long.MIN_VALUE` for `maxDate` will tell SublimePicker to keep future dates open for selection.

Note: The comment above `setDateRange(long, long)` is wrong. Passing `-1L` will not work as intended. The relevant check is performed here: https://github.com/vikramkakkar/SublimePicker/blob/master/sublimepickerlibrary/src/main/java/com/appeaser/sublimepickerlibrary/SublimePicker.java#L515

Pass `Long.MIN_VALUE` for whichever bound you wish to keep open: `minDate`/`maxDate`.

**Comment by Rainer-Lang** [comment]
@vikramkakkar Working. Thanks.

**Comment by rishabhsri20** [comment]
@Rainer-Lang where to set these limits?? I cant find any code.
