### ISSUE TITLE
Gradle Dependency

### ISSUE THREAD

**Issue by pyraego** [vikramkakkar/SublimePicker#8]
Is there a gradle dependency available for this library?

**Comment by pyraego** [comment]
Found it 

compile 'com.appeaser.sublimepickerlibrary:sublimepickerlibrary:1.0.0'

**Comment by ParitoshBh** [comment]
Is there any version update to this one?

**Comment by jitpack-io** [comment]
Hi all

We're seeing some users installing SublimePicker using JitPack. The latest commit works fine:
https://jitpack.io/#vikramkakkar/SublimePicker/bb405d8d14
but would be also nice to have some GitHub releases to make it easier.

**Comment by vikramkakkar** [comment]
@ParitoshBh Hi, SublimePicker has been updated..
