### ISSUE TITLE
Not finding ways to remove more option

### ISSUE THREAD

**Issue by Abish-R** [vikramkakkar/SublimePicker#94]
Not finding ways to remove more option.

Is there a way to block more options which is available in top right corner which facilitate(Repeat options)

**Comment by Abish-R** [comment]
sublimeOptions.setDisplayOptions(SublimeOptions.ACTIVATE_DATE_PICKER | SublimeOptions.ACTIVATE_TIME_PICKER);

**Comment by TrueFinch** [comment]
@Abish-R Did you finally find any way to do this?

**Comment by Abish-R** [comment]
Sorry for late reply @TrueFinch . You might have fixed the issue... I have modified the library code. I was not finding any other option to do it.
